SEED: 0
EXPERIMENT: 'default_experiment'
TRAIN:
    batch_size: 32
    epochs: 60
    num_workers: 1
    input_track_size: 10
    output_track_size: 20
    lr: 0.0001
    lr_decay: 1
    lr_drop: true
    aux_weight: 0.2
    val_frequency: 5
    optimizer: "adam"
    max_grad_norm: 1.0
DATA:
    train_datasets:
        - AMASS, D3DPW, H36m, JTA, NBA, JRDB # specify used datasets in UniHuMotion cache format
    chunk_size: 4
MODEL:
    token_num: 81 # Traj (1) + 2d/3d BB (2) + 3d P (39) + 2d P(39)
    num_layers_local: 6
    num_layers_global: 4
    num_heads: 4
    dim_hidden: 128 
    dim_feedforward: 512 
    type: "transmotion"
    eval_single: false
    checkpoint: ""
    output_scale: 1 
